version: '3.8'

services:
  eureka-server:
    image: eurekaserver-image  # 사용할 이미지 이름 (필요시 빌드 설정을 추가해야 함)
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring-cloud-network
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_SERVER_ENABLE_SELF_PRESERVATION=false

  api-gateway:
    image: apigateway-image  # 사용할 이미지 이름 (필요시 빌드 설정을 추가해야 함)
    container_name: api-gateway
    build:
      context: ./api-gateway  # API Gateway Dockerfile 위치
    ports:
      - "8000:8000"
    networks:
      - spring-cloud-network
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

networks:
  spring-cloud-network:
    driver: bridge
