server:
  port: 8083  # group-service? ???? ??

spring:
  application:
    name: group-service  # ?????? ??? group-service? ?? (Eureka ?? ? ??)

  config:
    import: "optional:configserver:"  # ?? Config ???? ??? ????? ?? (Config ??? ??? ?? ??)

  datasource:
    url: jdbc:mysql://localhost:3306/festival_db
    username: festival_user
    password: festival_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false



eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}  # Eureka? ???? ?? ???? ID (?????? ??? ?? ??? ??)
    prefer-ip-address: true  # ??? ?? ?? IP ??? ???? Eureka? ??

  client:
    register-with-eureka: true  # ? ???(user-service)? Eureka? ???? ??
    fetch-registry: true  # Eureka?? ?? ???? ????? ???? ??
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka ?? URL (?? ??? 8761)
