server:
  port: 8081
spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/user-db?authSource=admin

  config:
    import: "optional:configserver:"
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


jwt :
  expiration_time: 86400000 #1일
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa


management:
  endpoints:
    web:
      exposure:
        include: configprops, env  # configprops와 env 엔드포인트 활성화
