server:
  port: 8081
spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/user-db?authSource=admin

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka