version: '3.8'

services:
  eureka-server:
    build:
      context: ./  # Dockerfile이 위치한 폴더
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring-cloud-network
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

networks:
  spring-cloud-network:
    driver: bridge
