server:
  port: 9001

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: data-collection-service
          uri: lb://data-collection-service
          predicates:
            - Path=/api/collection/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
