server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: data-collection-service
          uri: lb://DATA-COLLECTION
          predicates:
            - Path=/api/data-collection/**
        - id: api-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
