spring:
  datasource:
    url: jdbc:mysql://mysql:3306/festival_db  # Docker MySQL 컨테이너에 연결
    username: festival_user                   # MySQL 사용자 이름
    password: festival_password               # MySQL 사용자 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 필요에 따라 설정, 개발 시에는 'update', 프로덕션에서는 'validate' 등으로 설정
    properties:
      hibernate:
        format_sql: true
        show_sql: true  # SQL 쿼리를 로그에 출력하여 디버깅에 도움

docker:
  mysql:
    root-password: root_password
    database: festival_db
    username: festival_user
    password: festival_password

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG  # JDBC 연결 로그를 확인하고자 할 때 사용 (선택사항)
