server:
  port: 8080

spring:
  application:
    name: data-collection

  datasource:
    url: jdbc:mysql://localhost:3306/festival_db
    username: festival_user
    password: festival_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  profiles:
    active: local

elasticsearch:
  host: http://localhost:9200

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
