server:
  port: 8082  # match-service? ???? ??

spring:
  application:
    name: match-service  # ?????? ??? match-service? ?? (Eureka ?? ? ??)
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/user-db?authSource=admin  # MongoDB ?? URI (?? MongoDB?? ??? ?? admin DB ??)
  config:
    import: "optional:configserver:"  # ?? Config ???? ??? ????? ?? (Config ??? ??? ?? ??)

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}  # Eureka? ???? ?? ???? ID (?????? ??? ?? ??? ??)
    prefer-ip-address: true  # ??? ?? ?? IP ??? ???? Eureka? ??

  client:
    register-with-eureka: true  # ? ???(user-service)? Eureka? ???? ??
    fetch-registry: true  # Eureka?? ?? ???? ????? ???? ??
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka ?? URL (?? ??? 8761)
